sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hsp
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tQBrm63d78XEecQQywP
    access-key-secret: aJv4zsI6SnZEIQfOkxcek0sY5pb72n
    bucket-name: tsq-web-tlias
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx4d28e67f40744514
    secret: d7e1a643e1a9ad3ba25ef5156f20adac